// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.1
// source: proto/student_structure.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"id" orm:"pk;column(id);auto"`         
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" orm:"column(name)"`      
	Age           uint64                 `protobuf:"varint,3,opt,name=Age,proto3" json:"age" orm:"column(age)"`       
	User          *User                  `protobuf:"bytes,4,opt,name=User,proto3" json:"user" orm:"rel(fk);column(user)"`      
	Course        *Course                `protobuf:"bytes,5,opt,name=Course,proto3" json:"course" orm:"rel(fk);column(course)"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_proto_student_structure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_structure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_proto_student_structure_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Student) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Student) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

var File_proto_student_structure_proto protoreflect.FileDescriptor

var file_proto_student_structure_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x87, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x41,
	0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_student_structure_proto_rawDescOnce sync.Once
	file_proto_student_structure_proto_rawDescData = file_proto_student_structure_proto_rawDesc
)

func file_proto_student_structure_proto_rawDescGZIP() []byte {
	file_proto_student_structure_proto_rawDescOnce.Do(func() {
		file_proto_student_structure_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_student_structure_proto_rawDescData)
	})
	return file_proto_student_structure_proto_rawDescData
}

var file_proto_student_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_student_structure_proto_goTypes = []any{
	(*Student)(nil), // 0: proto.Student
	(*User)(nil),    // 1: proto.User
	(*Course)(nil),  // 2: proto.Course
}
var file_proto_student_structure_proto_depIdxs = []int32{
	1, // 0: proto.Student.User:type_name -> proto.User
	2, // 1: proto.Student.Course:type_name -> proto.Course
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_student_structure_proto_init() }
func file_proto_student_structure_proto_init() {
	if File_proto_student_structure_proto != nil {
		return
	}
	file_proto_user_structure_proto_init()
	file_proto_course_structure_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_student_structure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_student_structure_proto_goTypes,
		DependencyIndexes: file_proto_student_structure_proto_depIdxs,
		MessageInfos:      file_proto_student_structure_proto_msgTypes,
	}.Build()
	File_proto_student_structure_proto = out.File
	file_proto_student_structure_proto_rawDesc = nil
	file_proto_student_structure_proto_goTypes = nil
	file_proto_student_structure_proto_depIdxs = nil
}
